Repository AY2324S1-CS2103T-T17-2/tp, pull requests merged in 2023-11, with the labels that each got.

#143 Update UG for add, list, filter commands
  docs/UserGuide.md
  docs/images/add-command/AddCommandError.png
  docs/images/add-command/AfterAddCommand.png
  docs/images/add-command/BeforeAddCommand.png
  docs/images/filter-command/AfterFilterCommand.png
  docs/images/filter-command/FilterByPI.png
  docs/images/list-command/ListCommand.png
Labels: documentation, type.Task, priority.High

#135 Add notes field
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnremarkCommandParser.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/ui/CompanyDetailCard.java
  src/main/resources/view/CompanyDetailCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateCompanyAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCompanyDescriptorTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnremarkCommandParserTest.java
  src/test/java/seedu/address/model/company/CompanyTest.java
  src/test/java/seedu/address/model/company/RemarkTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
  src/test/java/seedu/address/testutil/CompanyUtil.java
  src/test/java/seedu/address/testutil/EditCompanyDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalCompanies.java
Labels: priority.Medium

#144 Update error messages for Filter Command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/company/ApplicationStatus.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
Labels: enhancement

#147 Update error messages
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/company/ApplicationStatus.java
  src/main/java/seedu/address/model/company/Deadline.java
  src/main/java/seedu/address/model/company/Name.java
  src/main/java/seedu/address/model/company/Phone.java
Labels: type.Enhancement, type.Bug

#150 Update header of landing page
  docs/index.md
Labels: type.Bug

#149 Edit: Improve error message
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: enhancement

#151 RemarkCommand: edit ui message
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/UnremarkCommandParser.java
  src/test/java/seedu/address/logic/parser/UnremarkCommandParserTest.java
Labels: severity.VeryLow

#154 Update UG
  docs/UserGuide.md
  docs/images/add-command/AddCommandError.png
  docs/images/add-command/AddCommandError_2.png
  docs/images/add-command/AfterAddCommand.png
  docs/images/add-command/BeforeAddCommand.png
  docs/images/filter-command/FilterCommandError.png
Labels: documentation

#153 Unremark feature
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/UnremarkCommandParser.java
  src/main/java/seedu/address/model/company/Remark.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/UnremarkCommandParserTest.java
Labels: type.Bug

#157 Update bootstrap alerts for icons
  docs/UserGuide.md
Labels: documentation

#142 Documentation: Update UG
  docs/UserGuide.md
  docs/images/EditDemo1.png
  docs/images/EditDemo2.png
  docs/images/edit-command/EditDemo1.png
  docs/images/edit-command/EditDemo2.png
  docs/images/edit-command/EditErrMsg.png
  docs/images/remark-command/RemarkDemo1.png
  docs/images/remark-command/RemarkDemo2.png
  docs/images/remark-command/RemarkErrMsg.png
  docs/images/remark-command/UnremarkDemo1.png
  docs/images/remark-command/UnremarkDemo2.png
  docs/images/remark-command/UnremarkErrMsg.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
Labels: documentation

#156 Bug fixes #1
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/ApplicationStatus.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/Email.java
  src/main/java/seedu/address/model/company/Name.java
  src/main/java/seedu/address/model/company/Phone.java
  src/main/java/seedu/address/model/company/RecruiterName.java
  src/main/java/seedu/address/model/company/Role.java
  src/main/java/seedu/address/model/company/UniqueCompanyList.java
  src/main/java/seedu/address/model/company/predicates/ApplicationStatusPredicate.java
  src/main/java/seedu/address/model/company/predicates/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/company/CompanyTest.java
  src/test/java/seedu/address/model/company/PhoneTest.java
  src/test/java/seedu/address/model/company/predicates/ApplicationStatusPredicateTest.java
  src/test/java/seedu/address/model/company/predicates/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/address/testutil/Assert.java
Labels: type.Bug, severity.High

#166 Fix prefix bug
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
Labels: bugfix

#165 Update sort ug
  docs/UserGuide.md
  docs/images/sort-command/AfterSorting.png
  docs/images/sort-command/BeforeSorting.png
  docs/images/sort-command/SortError.png
  src/main/java/seedu/address/logic/commands/SortCommand.java
Labels: documentation

#167 Remark: update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/RemarkActivityDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/RemarkActivityDiagram.png
  docs/images/edit-command/EditErrMsg.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: documentation

#168 Update edge cases for company fields
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/company/Name.java
  src/main/java/seedu/address/model/company/Phone.java
  src/main/java/seedu/address/model/company/RecruiterName.java
  src/main/java/seedu/address/model/company/Role.java
  src/main/resources/view/CompanyDetailCard.fxml
  src/main/resources/view/CompanyListCard.fxml
Labels: type.Enhancement, type.Bug

#171 Update user guide
  docs/UserGuide.md
  docs/images/add-command/AddCommandError2.png
  docs/images/add-command/AddCommandError_2.png
  src/main/java/seedu/address/model/company/ApplicationStatus.java
Labels: documentation, bugfix

#177 Implement Help Command
  build.gradle
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High

#228 Fix bug for Phone field
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/company/Phone.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/company/PhoneTest.java
Labels: bugfix

#226 Update UG bugs
  docs/UserGuide.md
  docs/images/quick-start/java11.png
  docs/images/ui-intro/uiIntro.png
Labels: documentation, bugfix

#227 Edit PPP draft
  docs/team/tayruxin.md
Labels: documentation

#230 Bugfix/UI bug find
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
Labels: bugfix

#229 Update user guide
  docs/UserGuide.md
  docs/images/quick-start/launchLinkMeIn.png
Labels: documentation, bugfix

#231 Edit UG formating
  docs/UserGuide.md
Labels: documentation

#242 Update image and typo on landing page
  docs/images/Ui.png
  docs/index.md
  src/main/resources/view/MainWindow.fxml
Labels: documentation, bugfix

#241 Update all sections of PPP, except DG section
  docs/team/glendachong.md
Labels: documentation

#246 Update PPP
  docs/team/alientian.md
Labels: documentation

#243 Update PPP
  docs/team/papataco14.md
Labels: documentation

#245 Fix typo for find result
  src/main/java/seedu/address/logic/Messages.java
Labels: bug.low

#236 Fix index error msg
  src/main/java/seedu/address/logic/Messages.java
Labels: bugfix

#232 Bug fixes of alphanumerics
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/Name.java
  src/main/java/seedu/address/model/company/RecruiterName.java
  src/main/java/seedu/address/model/company/Role.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/stubs/ModelStub.java
  src/test/java/seedu/address/logic/commands/stubs/ModelStubAcceptingCompanyAdded.java
  src/test/java/seedu/address/logic/commands/stubs/ModelStubWithCompanyInFilteredCompanyList.java
  src/test/java/seedu/address/logic/commands/stubs/ModelStubWithCompanyNotInFilteredCompanyList.java
  src/test/java/seedu/address/logic/commands/testdata/FindCommandTestCompanies.java
  src/test/java/seedu/address/model/company/NameTest.java
  src/test/java/seedu/address/model/company/RecruiterNameTest.java
  src/test/java/seedu/address/model/company/RoleTest.java
Labels: bugfix

#233 Remark: bug fixes
  docs/UserGuide.md
  docs/images/remark-command/RemarkDemo1.png
  docs/images/remark-command/RemarkDemo2.png
  docs/images/remark-command/UnremarkDemo1.png
  docs/images/remark-command/UnremarkDemo2.png
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCompanyDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/CompanyUtil.java
  src/test/java/seedu/address/testutil/EditCompanyDescriptorBuilder.java
Labels: bugfix

#255 Edit length of PPP
  docs/team/tayruxin.md
Labels: documentation

#249 Edit: fix bug for error message
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Labels: bugfix

#248 Fix clear result msg
  src/main/java/seedu/address/logic/commands/ClearCommand.java
Labels: bugfix, bug.low

#244 Fix sort command error
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: bug.low

#260 Update UG
  docs/UserGuide.md
  docs/images/CompanyDataLocation.png
Labels: documentation

#259 Fix error message bug for Add and Filter Command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/FilterCommand.java
Labels: bug.low

#254 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/DetailPanelClassDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/DetailPanelClassDiagram.png
  docs/images/ViewSequenceDiagram.png
Labels: documentation

#257 UG: add CLI description
  docs/UserGuide.md
  docs/images/cli-description/CliDescription1.png
  docs/images/cli-description/CommandFormat1.png
  docs/images/cli-description/CommandFormat2.png
Labels: documentation

#253 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/AddSequenceDiagram.png
  docs/images/FilterSequenceDiagram.png
Labels: documentation

#263 Fix headers and update acknowledgements
  docs/DeveloperGuide.md
Labels: documentation

#265 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#272 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#269 Display filtered list after Edit or Remark
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/UnremarkCommandParserTest.java
Labels: bugfix

#274 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#281 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#280 Update PPP for Glenda
  docs/team/glendachong.md
Labels: documentation

#266 Update DG Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/DuplicateActivityDiagram.puml
  docs/diagrams/DuplicateSequenceDiagram.puml
  docs/images/duplicate-detection/add-command/DuplicateActivityDiagram.png
  docs/images/duplicate-detection/edit-command/DuplicateSequenceDiagram.png
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
Labels: documentation

#278 Update DG: Add planned enhancements
  docs/DeveloperGuide.md
  docs/images/ModelClassDiagram.png
Labels: documentation

#268 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#282 Update tagline for duplicate section
  docs/UserGuide.md
Labels: documentation

#285 Update UG
  docs/UserGuide.md
Labels: documentation

#287 Fix DG diagram bugs
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/FilterSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/DeleteCompanySequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/FilterSequenceDiagram.png
  docs/images/ViewSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: documentation, bugfix

#284 UG: edit images
  docs/UserGuide.md
  docs/images/cli-description/CommandFormat1.png
  docs/images/cli-description/CommandFormat2.png
Labels: documentation

#291 Update UG: Minor edits
  docs/UserGuide.md
Labels: documentation

#283 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/images/AddActivityDiagram.png
Labels: documentation

#290 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/EditSequenceDiagram.png
  docs/team/alientian.md
Labels: documentation

#292 Update About Us Page
  docs/AboutUs.md
Labels: documentation

#303 Update introduction for PPP
  docs/team/glendachong.md
Labels: documentation

#299 Update user guide
  docs/UserGuide.md
Labels: documentation

#305 Update ug
  docs/UserGuide.md
  docs/images/quick-start/githubRelease.png
Labels: documentation, bugfix

#314 Fix find diagram
  docs/diagrams/FindCompanySequenceDiagram.puml
  docs/images/FindCompanySequenceDiagram.png
Labels: documentation, bug.low

#316 Update UG
  docs/UserGuide.md
Labels: documentation

#317 Update page breaks for UG
  docs/UserGuide.md
Labels: documentation

#313 Update view sequence diag
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ViewSequenceDiagram.png
Labels: documentation, bug.low

#318 Update page breaks again
  docs/UserGuide.md
Labels: documentation

#320 Update page break and hyperlinks
  docs/UserGuide.md
Labels: documentation

#302 DG: Add effort
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/EditSequenceDiagram.png
  docs/images/FindCompanySequenceDiagram.png
  docs/team/glendachong.md
Labels: documentation

#321 Update PPP
  docs/team/glendachong.md
Labels: documentation

#324 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#326 Fix minor errors in UG
  docs/UserGuide.md
Labels: bugfix

#328 Update grammar, typos and formatting for DG
  docs/DeveloperGuide.md
Labels: documentation

#329 Update tables format in UG
  docs/UserGuide.md
Labels: documentation

#333 Update quick start image in UG
  docs/images/quick-start/launchLinkMeIn.png
Labels: documentation

#335 Update glossary
  docs/DeveloperGuide.md
Labels: documentation
