Repository AY2324S1-CS2103T-T17-2/tp, pull requests merged in 2023-10, with the labels that each got.

#67 Update personal PPP
  docs/team/tayruxin.md
Labels: type.Task, priority.High

#63 Update User Guide
  docs/UserGuide.md
Labels: type.Task, priority.High

#73 Update site-wide settings
  docs/_config.yml
  docs/_sass/minima/_base.scss
Labels: type.Task, priority.High

#70 Update Product Scope-DG
  docs/DeveloperGuide.md
Labels: type.Task

#86 Update add command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/Deadline.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/duplicateCompanyAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCompanyDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/company/CompanyTest.java
  src/test/java/seedu/address/model/company/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/company/UniqueCompanyListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
  src/test/java/seedu/address/testutil/CompanyUtil.java
  src/test/java/seedu/address/testutil/TypicalCompanies.java
Labels: type.Task, priority.High

#88 Edit UI and test cases for AddCommand
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/Model.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/company/NameTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
Labels: type.Task, priority.High

#90 Add sort companies feature
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/Deadline.java
  src/main/java/seedu/address/model/company/UniqueCompanyList.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/ui/CompanyCard.java
  src/main/java/seedu/address/ui/CompanyDetailCard.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
  src/test/java/seedu/address/testutil/CompanyUtil.java
Labels: type.Task

#96 Update index.md
  docs/index.md
Labels: documentation

#101 Add test cases
  src/test/java/seedu/address/model/company/RecruiterNameTest.java
  src/test/java/seedu/address/model/company/RoleTest.java
Labels: type.Task

#104 Add priority field and remove tags
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/Priority.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/CompanyCard.java
  src/main/java/seedu/address/ui/CompanyDetailCard.java
  src/main/resources/view/CompanyDetailCard.fxml
  src/main/resources/view/CompanyListCard.fxml
  src/main/resources/view/DarkTheme.css
  src/test/data/JsonSerializableAddressBookTest/duplicateCompanyAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalCompaniesAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCompanyDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/company/CompanyTest.java
  src/test/java/seedu/address/model/company/UniqueCompanyListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
  src/test/java/seedu/address/testutil/CompanyBuilder.java
  src/test/java/seedu/address/testutil/CompanyUtil.java
  src/test/java/seedu/address/testutil/EditCompanyDescriptorBuilder.java
  src/test/java/seedu/address/testutil/TypicalCompanies.java
Labels: type.Task

#105 Edit UI for CompanyDetailCard
  src/main/resources/view/CompanyDetailCard.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#108 Add filter command
  src/main/java/seedu/address/logic/commands/FilterCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/ApplicationStatus.java
  src/main/java/seedu/address/model/company/ApplicationStatusPredicate.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/FilterCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
  src/test/java/seedu/address/model/company/ApplicationStatusPredicateTest.java
Labels: type.Task, priority.High

#107 Update dg
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/CompanyDetailPanelActivityDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/ViewSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/CompanyDetailPanelActivityDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/ViewSequenceDiagram.png
  docs/team/tayruxin.md
Labels: documentation

#109 Update UG: View, Delete, Find command
  docs/AfterDeleteCommand.png
  docs/AfterViewCommand.png
  docs/BeforeDeleteCommand.png
  docs/BeforeViewCommand.png
  docs/DeleteCommand.png
  docs/FindCommand.png
  docs/UserGuide.md
Labels: documentation

#112 Modify find command
  docs/DeveloperGuide.md
  docs/diagrams/FindCompanySequenceDiagram.puml
  docs/images/FindCompanySequenceDiagram.png
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/company/NameContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/testdata/FindCommandTestCompanies.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: documentation, priority.High

#111 Update UG for add, filter, list commands
  docs/AddCommand.png
  docs/ListCommand.png
  docs/UserGuide.md
  docs/images/add-command/AfterAddCommand.png
  docs/images/add-command/BeforeAddCommand.png
  docs/images/filter-command/FilterByPI.png
  docs/images/list-command/ListCommand.png
  docs/img.png
  docs/img_4.png
Labels: documentation

#117 Update DG for filter command
  docs/DeveloperGuide.md
  docs/diagrams/FilterSequenceDiagram.puml
  docs/images/FilterSequenceDiagram.png
Labels: documentation

#124 Update UG: Implementation of Edit
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/EditSequenceDiagram.png
  docs/team/tayruxin.md
Labels: documentation

#130 Update DG DeleteCommand Diag
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCompanySeqDiag.puml
  docs/images/DeleteCompanySequenceDiagram.png
Labels: documentation

#131 Improve error message for view and delete command
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
Labels: priority.Medium

#129 User guide: Add typography box styles for icons
  docs/UserGuide.md
  docs/assets/css/style.scss
Labels: documentation

#132 Adjust styles for kramdown compatibility
  docs/UserGuide.md
  docs/assets/css/style.scss
Labels: documentation

#138 Update error messages for Add Command fields
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/company/ApplicationStatus.java
  src/main/java/seedu/address/model/company/Deadline.java
  src/main/java/seedu/address/model/company/Email.java
  src/main/java/seedu/address/model/company/Name.java
  src/main/java/seedu/address/model/company/Phone.java
  src/main/java/seedu/address/model/company/Priority.java
  src/main/java/seedu/address/model/company/RecruiterName.java
  src/main/java/seedu/address/model/company/Role.java
  src/main/java/seedu/address/storage/JsonAdaptedCompany.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCompanyTest.java
Labels: enhancement, type.Task

#134 Edit UG introduction
  docs/UserGuide.md
  docs/assets/css/style.scss
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: documentation

#139 Modify SortCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/sort-command/AfterSorting.png
  docs/images/sort-command/BeforeSorting.png
  docs/images/sort-command/SortError.png
  docs/images/sort-command/TypeCommand.png
  src/main/java/seedu/address/logic/SortOrder.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/UniqueCompanyList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
  src/test/java/seedu/address/logic/parser/SortCommandParserTest.java
Labels: documentation, enhancement, priority.Medium

#136 Rename person diagrams
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#140 Handle Duplicates
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/company/Company.java
  src/main/java/seedu/address/model/company/UniqueCompanyList.java
  src/main/java/seedu/address/model/company/exceptions/DuplicateCompanyException.java
  src/test/data/JsonSerializableAddressBookTest/duplicateCompanyAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/model/company/CompanyTest.java
  src/test/java/seedu/address/testutil/CompanyUtil.java
  src/test/java/seedu/address/testutil/EditCompanyDescriptorBuilder.java
Labels: priority.High
